### ISSUE TITLE
FIFO patch

### ISSUE THREAD

**Issue by N-R-K** [bakkeby/sxiv-flexipatch#5]
I think you might be interested in [FIFO/pipe support](https://github.com/muennich/sxiv/pull/369) -- This patch allows you do read from stdin, so you can do something like ``curl 'https://link.to/image.png' | sxiv /dev/stdin`` which is much more saner than adding networking to the image viewer itself.

Also the xresources patch in this repo seems to be using NULL as a default fallback, as I mentioned [here](https://github.com/muennich/sxiv/pull/386#issuecomment-892850442) I believe it's better to use fg/bg as fallback in order to stay consistent with the default sxiv behavior.

**Comment by bakkeby** [comment]
Yes I see this has some overlap with the libcurl patch, but very little. I had to add a quick hack to make it work with the animated webp support, but other than that it seems to work.

> Also the xresources patch in this repo seems to be using NULL as a default fallback, as I mentioned here I believe it's better to use fg/bg as fallback in order to stay consistent with the default sxiv behavior.

Yes definitely using fg/bg as fallback makes perfect sense. Now there is this other patch which controls whether the foreground and background colours are swapped for the bar. It makes sense respect this swapping if it is falling back to using the normal fg/bg colours, but it does not make as much sense to do this if the user has specified separate colours for the bar via xresources. Because of this I intentionally set the default fallback to NULL so that I could differentiate between whether the user has defined separate colours for the bar or not. It falls back to the fg or bg colours later on if the background colours are NULL (i.e. not set via xresources). So it is merely defaulting to NULL for compatibility reasons.
